In [14]:
import torch
import torch.nn as nn
import numpy as np
from torch.autograd import Variable

In [6]:
forward=Variable(torch.zeros(10))
forward

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
forward.expand(10,10)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [39]:
c=torch.randint(0,5,size=(5,))
c.size(0)

5

In [ ]:
a=torch.randint(0,5,size=(5,5))
a

In [15]:
torch.max(a.expand(a.size(0),a.size(0)).t()[:3,:3],dim=0)

torch.return_types.max(
values=tensor([4, 4, 4]),
indices=tensor([2, 2, 2]))

In [24]:
b=torch.LongTensor([-1]).expand(10)
b_=[b]

In [27]:
a

tensor([1, 3, 4, 4, 2, 0, 3, 1, 1, 2])

In [25]:
b_.append(a)

In [34]:
a=torch.randint(0,5,size=(5,5))
a

tensor([[0, 1, 1, 2, 0],
        [0, 2, 3, 3, 3],
        [4, 4, 0, 2, 2],
        [4, 3, 0, 2, 0],
        [3, 4, 4, 0, 4]])

In [43]:
tags=[1,0,2,3,1]
a[torch.LongTensor(range(c.size(0))),tags]

tensor([1, 0, 0, 2, 4])

In [18]:
embedd=torch.randn(size=(32,5,128))
embedd

tensor([[[-1.1032, -0.2201,  0.0417,  ...,  0.8048, -1.7156, -1.6948],
         [-0.1618,  0.9146, -0.4252,  ..., -0.4482,  0.0149, -0.5817],
         [-0.8995, -0.4806,  0.6678,  ...,  1.7600, -1.2342, -0.3373],
         [ 1.4037,  0.1314, -0.3840,  ..., -0.7170,  0.4697, -1.2710],
         [ 1.3416, -1.4687,  0.3155,  ...,  0.5801, -1.5886,  0.7215]],

        [[-0.6928, -0.6399,  1.3488,  ...,  0.8086,  1.3309, -0.7301],
         [ 0.7498,  0.7454, -2.2668,  ..., -0.6475, -0.4826,  0.5821],
         [-0.2068, -0.3305,  1.4889,  ..., -0.6099, -0.6580,  0.3838],
         [-2.0785, -0.4974, -1.4631,  ..., -0.7480, -0.2731,  0.7450],
         [-0.5378,  1.6669,  0.7009,  ..., -0.2888,  0.0420,  1.2956]],

        [[ 0.0293,  0.4226,  0.4704,  ..., -1.4362, -1.2979,  2.3129],
         [-0.8465,  1.3146, -0.3355,  ...,  0.8780, -0.3600,  0.6345],
         [-0.3634, -0.3572, -0.7092,  ...,  1.3431,  0.3843,  0.9383],
         [-1.1377,  0.9980,  2.1894,  ..., -0.6741, -0.6323, -1.3789],
  

In [19]:
conv=nn.Conv1d(in_channels=128,out_channels=127,kernel_size=3)


In [26]:
result=conv(embedd.permute(0,2,1))
result.permute(0,2,1).shape

torch.Size([32, 3, 127])

In [27]:
result.shape


torch.Size([32, 127, 3])

Part 2
metrics

In [2]:
import re
import itertools

In [28]:
tags_actual = [
            ['O', 'O', 'O', 'O', 'O', 'O', 'B-PER.NAM', 'I-PER.NAM', 'O', 'O', 'O', 'O', 'O', 'O', 'O'],  # 1个实体
            ['O', 'B-PER.NAM', 'I-PER.NAM', 'I-PER.NAM', 'O', 'O', 'B-PER.NAM', 'I-PER.NAM', 'O', 'O']  # 2个实体
        ]


tags_predict = [
            ['O', 'O', 'O', 'O', 'O', 'O', 'B-PER.NAM', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O'],  # 错1个
            ['O', 'B-PER.NAM', 'I-PER.NAM', 'I-PER.NAM', 'O', 'O', 'O', 'O', 'O', 'O']  # 漏1个
        ]

In [29]:
tags_actual = list(itertools.chain(*tags_actual))
tags_actual = ''.join(list(map(lambda tag: tag[0], tags_actual)))
tags_actual

'OOOOOOBIOOOOOOOOBIIOOBIOO'

In [30]:
tags_predict = list(itertools.chain(*tags_predict))
tags_predict = ''.join(list(map(lambda tag: tag[0], tags_predict)))
tags_predict

'OOOOOOBOOOOOOOOOBIIOOOOOO'

In [25]:
regex = re.compile('BI*')

In [31]:
len(tags_predict)==len(tags_actual)


True

['6_8', '16_19', '21_23']

3

In [16]:
regex.finditer(tags_actual)

<re.Match object; span=(6, 8), match='BI'>
<re.Match object; span=(16, 19), match='BII'>
<re.Match object; span=(21, 23), match='BI'>


In [32]:
entity_predict = ['{}_{}'.format(m.start(), m.start() + len(m.group()))
                          for m in regex.finditer(tags_predict)]
entity_actual = ['{}_{}'.format(m.start(), m.start() + len(m.group()))
                         for m in regex.finditer(tags_actual)]

print(entity_actual)
print(entity_predict)

['6_8', '16_19', '21_23']
['6_7', '16_19']


In [33]:
correct_num = len(set(entity_predict) & set(entity_actual))
correct_num

1

In [35]:
actual_num = len(entity_actual)
actual_num

3

In [37]:
float(correct_num) / actual_num if actual_num else 0.

0.3333333333333333

In [3]:
a=np.var([2,4,8])
a

6.222222222222221

In [4]:
b=np.var([1,3,7])
b


6.222222222222222

Bert

In [1]:
from ner.Bert.bertcrf import BertCRF
model=BertCRF(bert_model_dir="../models/chinese-bert-wwm/",label_size=12,dropout_rate=0.2)
  

In [3]:
model.named_parameters()

<generator object Module.named_parameters at 0x0000017BF07BBD48>

In [5]:
for group in model.named_parameters():
    print(group[0])

bert_model.embeddings.word_embeddings.weight
bert_model.embeddings.position_embeddings.weight
bert_model.embeddings.token_type_embeddings.weight
bert_model.embeddings.LayerNorm.weight
bert_model.embeddings.LayerNorm.bias
bert_model.encoder.layer.0.attention.self.query.weight
bert_model.encoder.layer.0.attention.self.query.bias
bert_model.encoder.layer.0.attention.self.key.weight
bert_model.encoder.layer.0.attention.self.key.bias
bert_model.encoder.layer.0.attention.self.value.weight
bert_model.encoder.layer.0.attention.self.value.bias
bert_model.encoder.layer.0.attention.output.dense.weight
bert_model.encoder.layer.0.attention.output.dense.bias
bert_model.encoder.layer.0.attention.output.LayerNorm.weight
bert_model.encoder.layer.0.attention.output.LayerNorm.bias
bert_model.encoder.layer.0.intermediate.dense.weight
bert_model.encoder.layer.0.intermediate.dense.bias
bert_model.encoder.layer.0.output.dense.weight
bert_model.encoder.layer.0.output.dense.bias
bert_model.encoder.layer.0.outp

In [6]:
from transformers import BertTokenizer, BertModel


In [10]:
tokenizer=BertTokenizer.from_pretrained("../models/chinese-bert-wwm/")

In [11]:
#对文本进行转化
texts="我 好 喜 欢 你 啊"
encode=tokenizer.encode_plus(texts,max_length=128,padding="max_length",return_tensors="pt",truncation=True)
encode

{'input_ids': tensor([[ 101, 2769, 1962, 1599, 3614,  872, 1557,  102,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0,

In [32]:
b=[]
a=encode["input_ids"]
a

tensor([[ 101, 2769, 1962, 1599, 3614,  872, 1557,  102,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0]])

In [36]:
b.append(a)
b



[tensor([[ 101, 2769, 1962, 1599, 3614,  872, 1557,  102,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0,    0,    0]]),
 tensor([[ 101, 2769, 1962, 1599, 3614,  872, 1557,  102,    0,    0,    0,    0,
             0,    0,    0,    0,    

In [37]:
torch.cat(b)

tensor([[ 101, 2769, 1962, 1599, 3614,  872, 1557,  102,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0],
        [ 101, 2769, 1962, 1599, 3614,  872, 1557,  102,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0, 

In [38]:
text=["我","x","h","n"]
text[1:-1]

['x', 'h']